#!/bin/sh
autoreconf -f -i
./configure
make

PRJDIR=$(pwd)
TMPDIR=/tmp/
VERSION=$(./weborf --version | head -n 1 | cut -d\  -f2)



rm -rf $TMPDIR/weborf*
make clean
./configure
make dist
mv weborf-$VERSION.tar.gz $TMPDIR/weborf_$VERSION.orig.tar.gz
gpg --sign --armor --detach-sign $TMPDIR/weborf_$VERSION.orig.tar.gz
cd $TMPDIR
tar -xvvf weborf_$VERSION.orig.tar.gz
cd weborf-$VERSION
cp -r $PRJDIR/debian .
dpkg-buildpackage
