.TH Weborf 5 "Sep 30, 2020" "Minimal webserver"

.SH NAME
.B weborf.conf
\- configuration file for weborf daemon

.SH SYNOPSIS
/etc/weborf.conf
.br
/etc/weborf.d/*.conf

.SH DESCRIPTION
Weborf is a minimal webserver. Also has a limited support for webdav.
.br
Can be started as stand-alone or as system daemon. This manual page documents Weborf's configuration file, used only when it is started as daemon.
.br

.SH DESCRIPTION
Options are case sensitive. Immediately followed by the equal = sign, without any space between name and value.
Lines beginning with # will be ignored and treated as comments.
.P
When systemd is in use, every .conf file in /etc/weborf.d/ is used to start a different instance of weborf, with a different configuration. Otherwise the file /etc/weborf.conf is used to start a single instance of weborf.
.SS

.TP
.B indexes
By default weborf searches for index.html. Anyway it is possible to specify a different index file and also many index files. Name of the pages must be separated by a comma and between them there aren't spaces.

.TP
.B basedir
Default base directory used by the webserver. The default means that this will be used also when virtual hosts are enabled, if the requested host is unknown. Of course the user used for the webserver will need to have access to this directory.

.TP
.B use-cgi
Can be true or false. If false weborf will handle all files as normal files. Otherwise it will use the CGI protocol to execute some files.
Defaults to false.

.TP
.B use-mime
Can be true or false. If true weborf will send the Content-Type header to the clients. Turning it off will increase speed but might cause problems with some old clients.

.TP
.B cgi
List of extensions to consider as dynamic pages and binaries to execute them. It takes a file format and a path, comma separated, and the list can include more formats and paths. Eg: cgi=.php,/bin/phpexecutor,.sh,/bin/shellexecutor

.TP
.B auth-socket
Path of the unix socket that weborf will use to connect to the authentication server. When this is enabled, for every HTTP request weborf opens a connection to this socket, forwards the request, and the authentication daemon is in charge of deciding whether to accept or deny the request. Examples are provided in /usr/share/doc/weborf/examples.

.TP
.B cachedir
Will set the path of the directory used for caching. When this is enabled, weborf will cache PROPFIND and directory listing requests, making them faster.

.TP
.B user
Username of the user that will run the webserver. On Debian this is usually www-data.

.TP
.B group
Groupname of the group that will run the webserver. On Debian this is usually www-data.

.TP
.B port
The port to use.

.TP
.B key
Absolute path to the SSL key file. It must be used with the cert option.
.br
When set, weborf will use HTTPS instead of HTTP.

.TP
.B cert
Absolute path to the SSL certificate file. It must be used with the key option.
.br
When set, weborf will use HTTPS instead of HTTP.

.TP
.B virtual
This directive is used to enable virtualhosts.
The format is:
virtual=localhost=/var/www/,serverq.com=/var/www-alt/
.br
To run on multiple ports, more instances are needed.

.TP
.B start
If this is set to auto, when systemd is in use, the instance using this configuration file is considered as part of the weborf service and started/stopped along with it. It does nothing with other init systems.

.SS

.SH "SEE ALSO"
.BR weborf (1)

.SH WEB
.BR https://ltworf.github.io/weborf/

.SH AUTHORS
.nf
Salvo "LtWorf" Tomaselli <tiposchi@tiscali.it>
Salvo Rinaldi <salvin@anche.no>
.br
