.TH Weborf 5 "Sep 13, 2009" "Minimal webserver"

.SH NAME
.B weborf.conf
\- configuration file for weborf daemon

.SH SYNOPSIS
/etc/weborf.conf

.SH DESCRIPTION
Weborf is a minimal webserver. Also has a limited support for webdav.
.br
Can be started as stand-alone or as SystemV daemon. This manual page documents Weborf's configuration file, used only when it is started as daemon.
.br
On debian systems, the script to run weborf as a daemon is located into /usr/share/docs/weborf and has to be manually copied into /etc/init.d
.br
Weborf is released under the GNU General Public License version 3.

.SH DESCRIPTION
Options are case sensitive. Immediately followed by the equal = sign, without any space between name and value.
Lines beginning with # will be ignored and treated as comments.
.SS

.TP
.B indexes
By default weborf searches for index.html. Anyway it is possible to specify a different index file and also many index files. Name of the pages must be separated by a comma and between them there aren't spaces.

.TP
.B basedir
Default base directory used by the webserver. The default means that this will be used also when virtual hosts are enabled, if the requested host is unknown. Of course the user used for the webserver will need to have access to this directory.

.TP
.B use-cgi
Can be true or false. If false weborf will handle all files as normal files. Otherwise it will use the CGI protocol to execute some files.

.TP
.B cgi
List of extensions to consider as dynamic pages and binaries to execute them

.TP
.B auth-bin
Path of the binary that provides authentication to weborf

.TP
.B auth-socket
Path of the unix socket that weborf will use to connect to the authentication server

.TP
.B user
Username of the user that will run the webserver. On debian this is usually www-data.

.TP
.B virtual
This directive is used to enable virtualhosts. One line is needed for each port.
The format is:
virtual#port#domain1=basedir1,domain2=basedir2
.SS

.SH EXAMPLE
Example file can be found in /usr/share/doc/weborf/examples/weborf.conf

.SH "SEE ALSO"
.BR weborf (1)

.SH VERSION
.BR Weborf 0.12

.SH WEB
.BR http://galileo.dmi.unict.it/wiki/weborf/

.SH AUTHORS
.nf
Salvo "LtWorf" Tomaselli <tiposchi@tiscali.it>
Salvo Rinaldi <salvin@anche.no>
.br
