.TH Weborf 0.9 "Sep 11, 2008"

.SH NAME
.B weborf
\- Minimal webserver

.SH SYNOPSIS
.B "weborf "
[
.B options
]

.SH DESCRIPTION
\fBWeborf\fP  is a minimal webserver, can serve only GET and POST requests.

This manual page documents \fBWeborf\fP's command-line parameters.

\fBWeborf\fP is released under the GNU General Public License version 3.
.PP

.SH GENERAL COMMAND LINE USAGE

Short command-line switches begin with a "-", and verbose switches begin with a "--".

 The parameter must be separated by the switch using a space.

.SH COMMAND LINE OPTIONS

.TP
\fB\-b\fR, \fB\-\-basedir\fR
Must be followed by a valid directory. Weborf will use this directory as root directory, and won't send files located in parent dirs. But it is still possible for server-side scripts to read contents located anywhere on the filesystem. Links are also a workaround to exit from the base directory.

.TP
\fB\-a\fR, \fB\-\-auth\fR
Must be followed by a program who will handle authentication. It is possible to use a script for this purpose. It will have five parameters on its command line. In the following order: method, page, IP, username, password. A zero exit code will tell to weborf that the authentication was accepted. Since weborf will wait for the program's termination to determine if allow or deny access, a non terminating program will prevent weborf to reply to any request. If no path (absolute or relative) is specified, weborf will use the PATH variable.

.TP
\fB\-x\fR, \fB\-\-noexec\fR
When used, weborf will send .php and .bsh files instead of executing them and sending their output.

.TP
\fB\-i\fR, \fB\-\-ip\fR
Must be followed by a valid IP address (v6 or v4, depending on how weborf was compiled. Run weborf -h to know it), and weborf will accept only connections directed to that specific IP.
If the IP address provided isn't used by a network device on the host, weborf will terminate.
By default weborf listens to all IP addresses on the local host.

.TP
\fB\-p\fR, \fB\-\-port\fR
Must be followed by a valid port number (between 1 and 65535), and weborf will listen to incoming connection on the specified port.
If the port is already used weborf will terminate.
To use low port numbers (less than 1024) it is necessary to execute the process as root. Thus it isn't a good idea to run a webserver with root privileges, so it is possible to specify another user.

.TP
\fB\-u\fR
Must be followed by a valid uid, different from 0. Weborf will use this user to do his work, but will bind to the network port with the previous user. This mechanism is meant to let users execute it as root and use port 80, and then let it run without root privileges.

.TP
\fB\-d\fR
Runs weborf as a daemon. It will not terminate when it's father process terminates, and it will leave the shell free to receive commands.

.SH SCRIPTING
Weborf is able to send dinamically generated pages using php (if installed) or bash.
When a filename ends with ".bsh", weborf will use bash to execute this file before sending it to the client.
Same thing happens when a file ends with ".php"; if php-cli is installed weborf will use it to execute the file and send it to the client.

Scripts are able to read data sent from the browser inside the HTTP request using env vars. Var's names will correspond to HTTP fields, except that "-" will be replaced with "_".
POST vars are readeable using env vars too. There will be one var for every field, and there won't be any replacement in the name.
GET vars are passed to the script as command line options.

.SH "SEE ALSO"
.BR php (1), bash(1)

.SH VERSION
\fBWeborf\fP 0.9

.SH WEB
http://galileo.dmi.unict.it/wiki/weborf/

.SH AUTHORS
Salvo "LtWorf" Tomaselli <tiposchi@tiscali.it>
