#!/bin/bash
. testsuite/functions.sh

run_weborf -b site1 -p 12350 --yesexec --cgi .py,/usr/bin/python3

curl -vs http://localhost:12350/cgi.py
curl -vs -H 'If-None-Match: "1545650587"' http://localhost:12350/cgi.py | grep 1545650587
curl -vs http://localhost:12350/cgi.py\?ciccio | grep ciccio
curl -vs --data "lallallero" http://localhost:12350/cgi.py | grep lallallero
