#!/bin/bash
. testsuite/functions.sh

run_weborf -b site1 -p 12351 --index index.txt,index.dat

[[ $(curl -Lvs http://localhost:12351/sub1/) = $(cat site1/sub1/index.txt) ]]
[[ $(curl -Lvs http://localhost:12351/sub2/) = $(cat site1/sub2/index.dat) ]]

[[ $(curl -Lvs http://localhost:12351/sub1) = $(cat site1/sub1/index.txt) ]]
[[ $(curl -Lvs http://localhost:12351/sub2) = $(cat site1/sub2/index.dat) ]]
