#!/bin/bash
set -mex
cd $(dirname $0)

../weborf -b site1 -p 12347  --mime &
WEBORF_PID=$(jobs -p)

function cleanup () {
    kill -9 $WEBORF_PID
}
trap cleanup EXIT

curl -v http://127.0.0.1:12347/robots.txt |& grep Content-Type | grep text/
