#!/bin/bash
set -mex
cd $(dirname $0)

weborf -b site1 -p 12346  --mime &
WEBORF_PID=$(jobs -p)

curl -v http://127.0.0.1:12346/robots.txt
curl -v http://127.0.0.1:12346/robots.txt |& grep Content-Type | grep text/

kill -9 $WEBORF_PID
