#!/bin/bash
set -mex
cd $(dirname $0)

./weborf -b site1 -p 12345 &
WEBORF_PID=$(jobs -p)

ROBOTS=$(curl -s http://127.0.0.1:12345/robots.txt)

kill -9 $WEBORF_PID

[[ "$ROBOTS" = $(cat site1/robots.txt) ]]
